spring.application.name=driver-konnect-backend

# Database Configuration - Using environment variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Logging Configuration
logging.level.root=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type=ERROR
logging.level.org.hibernate.orm.connections.pooling=WARN

# Server Configuration
server.port=${SERVER_PORT:8080}

